"""Add TrialInvitation table

Revision ID: 89529b0301c5
Revises: 41f04fcd4910
Create Date: 2026-08-26 21:46:24.205905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89529b0301c5'
down_revision: Union[str, Sequence[str], None] = '41f04fcd4910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('trial_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_invitations_id'), 'trial_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_trial_invitations_patient_id'), 'trial_invitations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_trial_invitations_trial_id'), 'trial_invitations', ['trial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_invitations_trial_id'), table_name='trial_invitations')
    op.drop_index(op.f('ix_trial_invitations_patient_id'), table_name='trial_invitations')
    op.drop_index(op.f('ix_trial_invitations_id'), table_name='trial_invitations')
    op.drop_table('trial_invitations')
    # ### end Alembic commands ###
